VPATH = $(SRCDIR)

INCLUDE_DIRS = -I. -I$(SRCDIR) -I$(SRCDIR)/../core -I$(SRCDIR)/../device -I$(SRCDIR)/../periph

TARGET = libstm32usb.a

SRCS := \
	$(wildcard $(SRCDIR)/*.c)

OBJS := $(SRCS:.c=.o)
OBJS := $(notdir $(OBJS))

all: $(TARGET)

include $(OBJS:.o=.dep)

%.dep: %.c
	@set -e; rm -f $@; \
	$(CC) -MM $(CFLAGS) $< > $@.$$$$; \
	sed 's,\($*\)\.o[ :]*,\1.o $@ : ,g' < $@.$$$$ > $@; \
	$(RM) $@.$$$$

%.dep: %.s
	@set -e; rm -f $@; \
	$(CC) -MM $(ASFLAGS) $< > $@.$$$$; \
	sed 's,\($*\)\.o[ :]*,\1.o $@ : ,g' < $@.$$$$ > $@; \
	$(RM) $@.$$$$

$(TARGET): $(OBJS)
	$(AR) $(ARFLAGS) $@ $^
