VPATH = $(SRCDIR) $(SRCDIR)/core $(SRCDIR)/device $(SRCDIR)/periph

INCLUDE_DIRS = -I. -I$(SRCDIR) -I$(SRCDIR)/core -I$(SRCDIR)/device -I$(SRCDIR)/periph

TARGET = libstm32.a

SRCS := \
	$(SRCDIR)/core/core_cm3.c \
	$(SRCDIR)/device/startup_stm32f10x_ld.s \
	$(wildcard $(SRCDIR)/periph/*.c)
#	$(SRCDIR)/device/system_stm32f10x.c

OBJS := $(SRCS:.c=.o)
OBJS := $(OBJS:.s=.o)
OBJS := $(notdir $(OBJS))

all: $(TARGET)

-include $(OBJS:.o=.dep)

%.dep: %.c
	@set -e; rm -f $@; \
	$(CC) -MM $(CFLAGS) $< > $@.$$$$; \
	sed 's,\($*\)\.o[ :]*,\1.o $@ : ,g' < $@.$$$$ > $@; \
	$(RM) $@.$$$$

%.dep: %.s
	@set -e; rm -f $@; \
	$(CC) -MM $(ASFLAGS) $< > $@.$$$$; \
	sed 's,\($*\)\.o[ :]*,\1.o $@ : ,g' < $@.$$$$ > $@; \
	$(RM) $@.$$$$

$(TARGET): $(OBJS)
	$(AR) $(ARFLAGS) $@ $^
